"""Generate GeneratedVersion.swift from the stamped git version.

Replaces the GenerateVersion SPM build-tool plugin. The version comes from the
workspace status command (see bazel/workspace_status.sh, wired in .bazelrc),
which runs `git describe`. Reading the stable-status file keeps the git call
out of the build graph, the Bazel-idiomatic way to stamp a version.
"""

def _generated_version_impl(ctx):
    out = ctx.actions.declare_file(ctx.attr.out)
    ctx.actions.run_shell(
        inputs = [ctx.info_file],
        outputs = [out],
        arguments = [ctx.info_file.path, out.path],
        command = """
set -eu
ver=$(awk '/^STABLE_GIT_VERSION/ {print $2}' "$1")
[ -n "${ver:-}" ] || ver=unknown
{
  echo '// Auto-generated by the generated_version rule — do not edit.'
  echo 'enum GeneratedVersion {'
  echo "    static let value = \\"$ver\\""
  echo '}'
} > "$2"
""",
    )
    return [DefaultInfo(files = depset([out]))]

generated_version = rule(
    implementation = _generated_version_impl,
    attrs = {
        "out": attr.string(default = "GeneratedVersion.swift"),
    },
)
