// GENERATED by EmbedHostAppSourceTool — DO NOT EDIT.
// Source files live under `HostAppSource/` at the package root.
// Re-run `swift build` after editing them.
import Foundation

enum IOSAgentAppSource {
    static let code: String = _decodeUTF8(_hostAppCodeBase64, label: "AgentApp.swift")
    static let infoPlist: String = _decodeUTF8(_infoPlistBase64, label: "Info.plist")
}

enum IOSAppIconData {
    static let bytes: Data = _decodeData(_iconBase64, label: "AppIcon.png")
}

