import Foundation

/// Generates Swift source code that combines the original source file with a `@_cdecl` bridge
/// entry point, allowing the preview view to be loaded via `dlopen` + `dlsym`.
public enum BridgeGenerator {

    /// Generate combined source with DesignTimeStore + literal thunks + bridge entry point.
    ///
    /// - Parameters:
    ///   - originalSource: The full content of the original Swift source file.
    ///   - closureBody: The body of the `#Preview { ... }` closure (extracted from TRANSFORMED source).
    ///   - entryPoint: The name of the C-callable entry function (default: `"createPreviewView"`).
    /// - Returns: Tuple of (source code ready to compile, literal entries for diffing).
    public static func generateCombinedSource(
        originalSource: String,
        closureBody: String,
        previewIndex: Int = 0,
        entryPoint: String = "createPreviewView",
        platform: PreviewPlatform = .macOS,
        traits: PreviewTraits = PreviewTraits()
    ) -> (source: String, literals: [LiteralEntry]) {
        // Transform source to replace literals with DesignTimeStore lookups
        let thunkResult = ThunkGenerator.transform(source: originalSource)

        // Re-parse transformed source to get the closure body with DesignTimeStore calls
        let previews = PreviewParser.parse(source: thunkResult.source)
        let transformedClosureBody: String
        if previewIndex < previews.count {
            transformedClosureBody = previews[previewIndex].closureBody
        } else {
            transformedClosureBody = closureBody
        }

        let modifiers = traitModifiers(traits)
        let bridgeCode: String
        switch platform {
        case .macOS:
            bridgeCode = """
                import AppKit

                @_cdecl("\(entryPoint)")
                public func \(entryPoint)() -> UnsafeMutableRawPointer {
                    let view = SwiftUI.AnyView(
                        \(transformedClosureBody)\(modifiers)
                    )
                    let hostingView = NSHostingView(rootView: view)
                    return Unmanaged.passRetained(hostingView).toOpaque()
                }
                """
        case .iOS:
            bridgeCode = """
                import UIKit

                @_cdecl("\(entryPoint)")
                public func \(entryPoint)() -> UnsafeMutableRawPointer {
                    let view = SwiftUI.AnyView(
                        \(transformedClosureBody)\(modifiers)
                    )
                    let hostingController = UIHostingController(rootView: view)
                    return Unmanaged.passRetained(hostingController).toOpaque()
                }
                """
        }

        let combined = """
            // --- DesignTimeStore ---
            \(DesignTimeStoreSource.code)

            // --- Source (with literal thunks) ---
            \(thunkResult.source)

            // --- Preview bridge (generated by PreviewsMCP) ---
            \(bridgeCode)
            """

        return (source: combined, literals: thunkResult.literals)
    }

    // MARK: - Project Mode: Tier 1 (bridge-only)

    /// Generate bridge-only source for project mode (Tier 1).
    /// Imports the target module and creates the @_cdecl entry point.
    /// No DesignTimeStore or original source — no literal hot-reload.
    public static func generateBridgeOnlySource(
        moduleName: String,
        closureBody: String,
        entryPoint: String = "createPreviewView",
        platform: PreviewPlatform = .macOS,
        traits: PreviewTraits = PreviewTraits()
    ) -> String {
        let frameworkImport: String
        let hostCode: String

        switch platform {
        case .macOS:
            frameworkImport = "import AppKit"
            hostCode = """
                    let hostingView = NSHostingView(rootView: view)
                    return Unmanaged.passRetained(hostingView).toOpaque()
                """
        case .iOS:
            frameworkImport = "import UIKit"
            hostCode = """
                    let hostingController = UIHostingController(rootView: view)
                    return Unmanaged.passRetained(hostingController).toOpaque()
                """
        }

        let modifiers = traitModifiers(traits)
        return """
            import SwiftUI
            \(frameworkImport)
            @testable import \(moduleName)

            @_cdecl("\(entryPoint)")
            public func \(entryPoint)() -> UnsafeMutableRawPointer {
                let view = SwiftUI.AnyView(
                    \(closureBody)\(modifiers)
                )
                \(hostCode)
            }
            """
    }

    // MARK: - Project Mode: Tier 2 (overlay with .o linking)

    /// Generate overlay source for project mode (Tier 2).
    /// Includes the preview file with ThunkGenerator transforms + DesignTimeStore + bridge.
    /// The preview file is compiled as part of the target module (same -module-name),
    /// while other target files are linked as pre-built .o files.
    public static func generateOverlaySource(
        originalSource: String,
        closureBody: String,
        previewIndex: Int = 0,
        entryPoint: String = "createPreviewView",
        platform: PreviewPlatform = .macOS,
        traits: PreviewTraits = PreviewTraits()
    ) -> (source: String, literals: [LiteralEntry]) {
        // Same as generateCombinedSource — transform literals, generate bridge
        // The difference is in how the Compiler uses the result: with -module-name <TargetName>
        // and linking pre-built .o files for other target sources.
        return generateCombinedSource(
            originalSource: originalSource,
            closureBody: closureBody,
            previewIndex: previewIndex,
            entryPoint: entryPoint,
            platform: platform,
            traits: traits
        )
    }

    /// Build SwiftUI modifier chain for the given traits.
    private static func traitModifiers(_ traits: PreviewTraits) -> String {
        var mods = ""
        if let cs = traits.colorScheme {
            mods += "\n            .preferredColorScheme(.\(cs))"
        }
        if let dts = traits.dynamicTypeSize {
            mods += "\n            .dynamicTypeSize(.\(dts))"
        }
        return mods
    }
}
