import Foundation

/// Generates Swift source code that combines the original source file with a `@_cdecl` bridge
/// entry point, allowing the preview view to be loaded via `dlopen` + `dlsym`.
public enum BridgeGenerator {

    /// Generate combined source with DesignTimeStore + literal thunks + bridge entry point.
    ///
    /// - Parameters:
    ///   - originalSource: The full content of the original Swift source file.
    ///   - closureBody: The body of the `#Preview { ... }` closure from the original source.
    ///     Used as fallback if re-parsing the transformed source yields fewer previews than expected.
    ///   - previewIndex: 0-based index of which `#Preview` block to render (default: 0).
    ///   - entryPoint: The name of the C-callable entry function (default: `"createPreviewView"`).
    /// - Returns: Tuple of (source code ready to compile, literal entries for diffing).
    public static func generateCombinedSource(
        originalSource: String,
        closureBody: String,
        previewIndex: Int = 0,
        entryPoint: String = "createPreviewView",
        platform: PreviewPlatform = .macOS,
        traits: PreviewTraits = PreviewTraits(),
        setupModule: String? = nil,
        setupType: String? = nil
    ) -> (source: String, literals: [LiteralEntry]) {
        // Transform source to replace literals with DesignTimeStore lookups
        let thunkResult = ThunkGenerator.transform(source: originalSource)

        // Re-parse transformed source to get the closure body with DesignTimeStore calls
        let previews = PreviewParser.parse(source: thunkResult.source)
        let transformedClosureBody: String
        if previewIndex < previews.count {
            transformedClosureBody = previews[previewIndex].closureBody
        } else {
            transformedClosureBody = closureBody
        }

        let modifiers = traitModifiers(traits)
        let hasSetup =
            setupModule != nil && setupType != nil
            && isValidSwiftIdentifier(setupModule!) && isValidSwiftIdentifier(setupType!)
        let setupImport = hasSetup ? "import \(setupModule!)\n" : ""
        let setUpEntry = hasSetup ? setUpEntryPoint(setupType: setupType!) : ""
        let viewCode =
            hasSetup
            ? viewWithSetup(closureBody: transformedClosureBody, setupType: setupType!, modifiers: modifiers)
            : """
            {
                        return SwiftUI.AnyView(__PreviewBridge.wrap {
                            \(transformedClosureBody)
                        }\(modifiers))
                    }()
            """

        let bodyKindEntry = bodyKindEntryPoint(closureBody: transformedClosureBody)
        let bridgeCode: String
        switch platform {
        case .macOS:
            bridgeCode = """
                import AppKit
                \(setupImport)
                \(setUpEntry)
                @_cdecl("\(entryPoint)")
                public func \(entryPoint)() -> UnsafeMutableRawPointer {
                    let view = \(viewCode)
                    let hostingView = NSHostingView(rootView: view)
                    return Unmanaged.passRetained(hostingView).toOpaque()
                }

                \(bodyKindEntry)
                """
        case .iOS:
            bridgeCode = """
                import UIKit
                \(setupImport)
                \(setUpEntry)
                @_cdecl("\(entryPoint)")
                public func \(entryPoint)() -> UnsafeMutableRawPointer {
                    let view = \(viewCode)
                    let hostingController = UIHostingController(rootView: view)
                    return Unmanaged.passRetained(hostingController).toOpaque()
                }

                \(bodyKindEntry)
                """
        }

        let combined = """
            // --- DesignTimeStore ---
            \(DesignTimeStoreSource.code)

            // --- Preview bridge helper (generated by PreviewsMCP) ---
            \(PreviewBridgeSource.code(for: platform))

            // --- Source (with literal thunks) ---
            \(thunkResult.source)

            // --- Preview bridge (generated by PreviewsMCP) ---
            \(bridgeCode)
            """

        return (source: combined, literals: thunkResult.literals)
    }

    // MARK: - Project Mode: Tier 1 (bridge-only)

    /// Generate bridge-only source for project mode (Tier 1).
    /// Imports the target module and creates the @_cdecl entry point.
    /// No DesignTimeStore or original source — no literal hot-reload.
    public static func generateBridgeOnlySource(
        moduleName: String,
        closureBody: String,
        entryPoint: String = "createPreviewView",
        platform: PreviewPlatform = .macOS,
        traits: PreviewTraits = PreviewTraits(),
        setupModule: String? = nil,
        setupType: String? = nil
    ) -> String {
        let frameworkImport: String
        let hostCode: String

        switch platform {
        case .macOS:
            frameworkImport = "import AppKit"
            hostCode = """
                    let hostingView = NSHostingView(rootView: view)
                    return Unmanaged.passRetained(hostingView).toOpaque()
                """
        case .iOS:
            frameworkImport = "import UIKit"
            hostCode = """
                    let hostingController = UIHostingController(rootView: view)
                    return Unmanaged.passRetained(hostingController).toOpaque()
                """
        }

        let modifiers = traitModifiers(traits)
        let hasSetup =
            setupModule != nil && setupType != nil
            && isValidSwiftIdentifier(setupModule!) && isValidSwiftIdentifier(setupType!)
        let setupImport = hasSetup ? "\nimport \(setupModule!)" : ""
        let setUpEntry = hasSetup ? "\n\n\(setUpEntryPoint(setupType: setupType!))\n" : ""
        let viewCode =
            hasSetup
            ? viewWithSetup(closureBody: closureBody, setupType: setupType!, modifiers: modifiers)
            : """
            {
                    return SwiftUI.AnyView(__PreviewBridge.wrap {
                        \(closureBody)
                    }\(modifiers))
                }()
            """

        let bodyKindEntry = bodyKindEntryPoint(closureBody: closureBody)

        return """
            import SwiftUI
            \(frameworkImport)
            @testable import \(moduleName)\(setupImport)

            // --- Preview bridge helper (generated by PreviewsMCP) ---
            \(PreviewBridgeSource.code(for: platform))
            \(setUpEntry)
            @_cdecl("\(entryPoint)")
            public func \(entryPoint)() -> UnsafeMutableRawPointer {
                let view = \(viewCode)
                \(hostCode)
            }

            \(bodyKindEntry)
            """
    }

    // MARK: - Project Mode: Tier 2 (overlay with .o linking)

    /// Generate overlay source for project mode (Tier 2).
    /// Includes the preview file with ThunkGenerator transforms + DesignTimeStore + bridge.
    /// The preview file is compiled as part of the target module (same -module-name),
    /// while other target files are linked as pre-built .o files.
    public static func generateOverlaySource(
        originalSource: String,
        closureBody: String,
        previewIndex: Int = 0,
        entryPoint: String = "createPreviewView",
        platform: PreviewPlatform = .macOS,
        traits: PreviewTraits = PreviewTraits(),
        setupModule: String? = nil,
        setupType: String? = nil
    ) -> (source: String, literals: [LiteralEntry]) {
        return generateCombinedSource(
            originalSource: originalSource,
            closureBody: closureBody,
            previewIndex: previewIndex,
            entryPoint: entryPoint,
            platform: platform,
            traits: traits,
            setupModule: setupModule,
            setupType: setupType
        )
    }

    // MARK: - __PreviewBridge.wrap
    //
    // The generated bridge passes the user's closure body to
    // `__PreviewBridge.wrap { <body> }` (declared in `PreviewBridgeSource`),
    // which dispatches through Swift overload resolution:
    //
    //   - SwiftUI bodies (any `V: SwiftUI.View`) match a `@ViewBuilder` generic
    //     overload — preserving every construct Xcode's `#Preview` accepts:
    //     `if #available`, leading `let`/`var` declarations, branches with
    //     different concrete types, etc. The `@ViewBuilder` attribute lifts
    //     statement-only restrictions via `_ConditionalContent`.
    //   - UIKit bodies (`UIView`, `UIViewController`, and their subclasses)
    //     match dedicated non-generic overloads that wrap the view in a
    //     `UIViewRepresentable` / `UIViewControllerRepresentable` bridge —
    //     matching what Xcode's `#Preview` macro does for UIKit bodies.
    //
    // This replaces an earlier design that declared a nested
    // `@ViewBuilder func __previewBody() -> some SwiftUI.View { <body> }`,
    // which rejected UIKit bodies with
    // "'ExampleUIView' does not conform to 'View'".
    //
    // Caveat: UIKit has no `@ViewBuilder` equivalent, so multi-statement
    // UIKit bodies require an explicit `return`. Same constraint applies to
    // Xcode's first-party `#Preview` macro for UIKit.

    /// Validate that a string is safe to interpolate as a Swift identifier or dotted module path.
    private static func isValidSwiftIdentifier(_ s: String) -> Bool {
        let pattern = #"^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)*$"#
        return s.range(of: pattern, options: .regularExpression) != nil
    }

    /// Generate the `@_cdecl("previewBodyKind")` entry point. The compiler picks the same
    /// `__PreviewBodyKindProbe.detect` overload that `__PreviewBridge.wrap` does, so the
    /// returned value reflects the outermost body kind: 1 = SwiftUI, 2 = UIView,
    /// 3 = UIViewController. Used by the daemon to skip the literal-only fast path for
    /// UIKit bodies (#160).
    private static func bodyKindEntryPoint(closureBody: String) -> String {
        """
        @_cdecl("previewBodyKind")
        public func previewBodyKind() -> Int32 {
            return __PreviewBodyKindProbe.detect {
                \(closureBody)
            }
        }
        """
    }

    /// Generate the `@_cdecl("previewSetUp")` entry point that bridges async setUp.
    private static func setUpEntryPoint(setupType: String) -> String {
        """
        @_cdecl("previewSetUp")
        public func previewSetUp() {
            let semaphore = DispatchSemaphore(value: 0)
            Task {
                try? await \(setupType).setUp()
                semaphore.signal()
            }
            semaphore.wait()
        }
        """
    }

    /// Generate view code with setup wrapping. The closure body is threaded through
    /// `__PreviewBridge.wrap` (which dispatches to SwiftUI / UIKit overloads via overload
    /// resolution) before being handed to the setup plugin's `wrap`. Traits are applied
    /// OUTSIDE the setup wrap so explicit overrides take precedence.
    private static func viewWithSetup(closureBody: String, setupType: String, modifiers: String) -> String {
        """
        {
                let innerView = __PreviewBridge.wrap {
                    \(closureBody)
                }
                let wrappedView = \(setupType).wrap(innerView)
                return SwiftUI.AnyView(
                    wrappedView\(modifiers)
                )
            }()
        """
    }

    /// Build SwiftUI modifier chain for the given traits.
    private static func traitModifiers(_ traits: PreviewTraits) -> String {
        var mods = ""
        if let cs = traits.colorScheme {
            mods += "\n            .preferredColorScheme(.\(cs))"
        }
        if let dts = traits.dynamicTypeSize {
            mods += "\n            .dynamicTypeSize(.\(dts))"
        }
        if let locale = traits.locale {
            mods += "\n            .environment(\\.locale, Locale(identifier: \"\(locale)\"))"
        }
        if let ld = traits.layoutDirection {
            mods += "\n            .environment(\\.layoutDirection, .\(ld))"
        }
        if let lw = traits.legibilityWeight {
            mods += "\n            .environment(\\.legibilityWeight, .\(lw))"
        }
        return mods
    }
}
