import Foundation

/// Reads the iOS agent-app artifacts (`AgentApp.swift`, `Info.plist`,
/// `AppIcon.png`) from a fixed location and emits a Swift source file
/// containing them as base64-encoded constants. Invoked by the
/// `EmbedHostAppSource` build-tool plugin (see
/// `Plugins/EmbedHostAppSource/EmbedHostAppSource.swift`).
///
/// Why base64 over `[UInt8]` arrays: the raw bytes total ~88KB; a
/// `[UInt8]` literal would be ~530KB of Swift source and slow to
/// compile. Base64 keeps the output ~120KB and readable.
///
/// Why not just use raw string literals: the iOS agent app source
/// contains `"""` and other delimiters that would require careful
/// escaping. Base64 sidesteps the entire encoding-concerns space.
///
/// Byte-equivalence with the prior hand-written `IOSAgentAppSource.swift`
/// blob is the load-bearing acceptance gate for #7
/// (`IOSAgentBuilderHashTests.hashIsStable`). Decoding base64 → UTF-8 →
/// `String` is byte-identical with the prior triple-quoted string-
/// literal source IFF the input files contain exactly those bytes.
@main
enum EmbedHostAppSourceTool {
    static func main() throws {
        let args = CommandLine.arguments
        guard args.count == 9 else {
            fail(
                "usage: \(args.first ?? "tool") <agentSource> <infoPlist> <iconPng> "
                    + "<shellSource> <shellInfoPlist> <shellEntitlements> <shellIconPng> <output>")
        }

        let agentAppB64 = readBase64(args[1])
        let infoPlistB64 = readBase64(args[2])
        let iconB64 = readBase64(args[3])
        let shellCodeB64 = readBase64(args[4])
        let shellInfoPlistB64 = readBase64(args[5])
        let shellEntitlementsB64 = readBase64(args[6])
        let shellIconB64 = readBase64(args[7])
        let outputPath = args[8]

        // Interpolating these directly into a Swift source string is safe
        // because the base64 alphabet (`A-Z a-z 0-9 + /` plus `=` padding) is
        // a strict subset of ASCII printable with no `"`, no `\`, no
        // interpolation triggers. If this tool is ever extended to embed
        // non-base64 payloads, the substitution would need explicit escaping.
        let generated = """
            // GENERATED by EmbedHostAppSourceTool — DO NOT EDIT.
            // Source files live under `ios-host/` at the package root.
            // Re-run `swift build` after editing them.
            import Foundation

            enum IOSAgentAppSource {
                static let code: String = _decodeUTF8(_agentAppCodeBase64, label: "AgentApp.swift")
                static let infoPlist: String = _decodeUTF8(_infoPlistBase64, label: "Info.plist")
            }

            enum IOSAppIconData {
                static let bytes: Data = _decodeData(_iconBase64, label: "AppIcon.png")
            }

            enum IOSShellAppSource {
                static let code: String = _decodeUTF8(_shellCodeBase64, label: "shell/ShellMain.m")
                static let infoPlist: String = _decodeUTF8(_shellInfoPlistBase64, label: "shell/Info.plist")
                static let entitlements: String = _decodeUTF8(_shellEntitlementsBase64, label: "shell/Shell.entitlements")
                static let iconBytes: Data = _decodeData(_shellIconBase64, label: "shell/AppIcon.png")
            }

            private let _agentAppCodeBase64 = "\(agentAppB64)"
            private let _infoPlistBase64 = "\(infoPlistB64)"
            private let _iconBase64 = "\(iconB64)"
            private let _shellCodeBase64 = "\(shellCodeB64)"
            private let _shellInfoPlistBase64 = "\(shellInfoPlistB64)"
            private let _shellEntitlementsBase64 = "\(shellEntitlementsB64)"
            private let _shellIconBase64 = "\(shellIconB64)"

            private func _decodeData(_ b64: String, label: String) -> Data {
                guard let data = Data(base64Encoded: b64) else {
                    preconditionFailure(
                        "EmbedHostAppSourceTool produced invalid base64 for \\(label) — rerun `swift build`."
                    )
                }
                return data
            }

            private func _decodeUTF8(_ b64: String, label: String) -> String {
                String(decoding: _decodeData(b64, label: label), as: UTF8.self)
            }

            """

        do {
            try Data(generated.utf8).write(to: URL(fileURLWithPath: outputPath))
        } catch {
            fail("could not write \(outputPath): \(error.localizedDescription)")
        }
    }

    /// Emit a stderr line and exit non-zero. Build-tool failures should
    /// be diagnosable from CI logs without a Swift backtrace.
    static func fail(_ message: String) -> Never {
        FileHandle.standardError.write(Data("EmbedHostAppSourceTool: \(message)\n".utf8))
        exit(1)
    }

    static func readBase64(_ path: String) -> String {
        do {
            let data = try Data(contentsOf: URL(fileURLWithPath: path))
            return data.base64EncodedString()
        } catch {
            fail("could not read \(path): \(error.localizedDescription)")
        }
    }
}
