import Foundation

/// Reads the iOS host-app artifacts (`HostApp.swift`, `Info.plist`,
/// `AppIcon.png`) from a fixed location and emits a Swift source file
/// containing them as base64-encoded constants. Invoked by the
/// `EmbedHostAppSource` build-tool plugin (see
/// `Plugins/EmbedHostAppSource/main.swift`).
///
/// Why base64 over `[UInt8]` arrays: the raw bytes total ~88KB; a
/// `[UInt8]` literal would be ~530KB of Swift source and slow to
/// compile. Base64 keeps the output ~120KB and readable.
///
/// Why not just use raw string literals: the iOS host app source
/// contains `"""` and other delimiters that would require careful
/// escaping. Base64 sidesteps the entire encoding-concerns space.
///
/// Byte-equivalence with the prior hand-written `IOSHostAppSource.swift`
/// blob is the load-bearing acceptance gate for #7
/// (`IOSHostBuilderHashTests.hashIsStable`). Decoding base64 → UTF-8 →
/// `String` is byte-identical with the prior triple-quoted string-
/// literal source IFF the input files contain exactly those bytes.

let args = CommandLine.arguments
guard args.count == 5 else {
    FileHandle.standardError.write(
        Data("usage: \(args[0]) <hostAppSwift> <infoPlist> <iconPng> <output>\n".utf8))
    exit(1)
}

let hostAppPath = args[1]
let infoPlistPath = args[2]
let iconPngPath = args[3]
let outputPath = args[4]

func readBase64(_ path: String) throws -> String {
    let data = try Data(contentsOf: URL(fileURLWithPath: path))
    return data.base64EncodedString()
}

let hostAppB64 = try readBase64(hostAppPath)
let infoPlistB64 = try readBase64(infoPlistPath)
let iconB64 = try readBase64(iconPngPath)

let generated = """
    // GENERATED by EmbedHostAppSourceTool — DO NOT EDIT.
    // Source files live under `HostAppSource/` at the package root.
    // Re-run `swift build` after editing them.
    import Foundation

    enum IOSHostAppSource {
        static let code: String = _decodeUTF8(_hostAppCodeBase64)
        static let infoPlist: String = _decodeUTF8(_infoPlistBase64)
    }

    enum IOSAppIconData {
        static let bytes: Data = Data(base64Encoded: _iconBase64)!
    }

    private let _hostAppCodeBase64 = "\(hostAppB64)"
    private let _infoPlistBase64 = "\(infoPlistB64)"
    private let _iconBase64 = "\(iconB64)"

    private func _decodeUTF8(_ b64: String) -> String {
        let data = Data(base64Encoded: b64)!
        return String(decoding: data, as: UTF8.self)
    }

    """

try Data(generated.utf8).write(to: URL(fileURLWithPath: outputPath))
